# Generated by Django 6.0.5 on 2026-05-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='章節編號')),
                ('title', models.CharField(max_length=100, verbose_name='章節名稱')),
            ],
            options={
                'verbose_name': '章節',
                'verbose_name_plural': '章節',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='題幹')),
                ('block', models.TextField(blank=True, verbose_name='程式碼區塊')),
                ('hint', models.TextField(blank=True, verbose_name='解析')),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], default='medium', max_length=10, verbose_name='難易度')),
                ('is_custom', models.BooleanField(default=False, verbose_name='本組設計')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.chapter', verbose_name='所屬章節')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='選項文字')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否為正解')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='所屬題目')),
            ],
            options={
                'verbose_name': '選項',
                'verbose_name_plural': '選項',
            },
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='作答者')),
                ('score', models.PositiveIntegerField(verbose_name='得分 (百分比)')),
                ('correct_count', models.PositiveIntegerField(verbose_name='答對題數')),
                ('total', models.PositiveIntegerField(verbose_name='總題數')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='作答秒數')),
                ('details_json', models.TextField(default='[]', verbose_name='詳細結果 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='quiz.chapter', verbose_name='章節')),
            ],
            options={
                'verbose_name': '作答紀錄',
                'verbose_name_plural': '作答紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
