# Generated by Django 6.0.5 on 2026-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='question_count',
            field=models.PositiveIntegerField(default=15, verbose_name='出題數'),
        ),
        migrations.AddField(
            model_name='quizrecord',
            name='spaced_rep',
            field=models.BooleanField(default=False, verbose_name='間隔學習'),
        ),
    ]
