# Generated by Django 6.0.5 on 2026-05-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizrecord_question_count_quizrecord_spaced_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_added',
            field=models.BooleanField(default=False, verbose_name='管理員新增'),
        ),
    ]
