# Generated by Django 6.0.5 on 2026-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_add_user_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='is_review',
            field=models.BooleanField(default=False, verbose_name='錯題複習模式'),
        ),
    ]
